In [2]:
import pandas as pd

In [3]:
# 예측 값 출력 예비 테스트
def make_bus_dict(dong):
    '''버스 노선 사전에서 동(key)를 넣으면 노선수(value)를 리턴하는 함수'''
    # 버스 노선 파일 불러오기
    bus_line_data = pd.read_excel("data/bus_line_data.xlsx")

    # 각 컬럼별 값들 리스트로 만들기
    adr_dong = list(bus_line_data['adr_dong'])
    bus_num = list(bus_line_data['버스노선수'])

    # dict로 키-값 형태로 저장하기
    bus_dict = {}

    for i in range(0, len(adr_dong)):
        bus_dict[adr_dong[i]] = bus_num[i]

    return bus_dict[dong]


data_dong = '고양동'
data_year = 2023
data_area = 85

# 버스노선수 dict에서 뽑기
data_bus = make_bus_dict(data_dong)

temp = {
    'year' : data_year,
    '전용면적' : data_area,
    '버스노선수' : data_bus,
    '가좌동' : 0,
    '고양동' : 0,
    '관산동' : 0,
    '대화동' : 0,
    '덕은동' : 0,
    '덕이동' : 0,
    '도내동' : 0,
    '동산동' : 0,
    '마두동' : 0,
    '백석동' : 0,
    '사리현동' : 0,
    '삼송동' : 0,
    '성사동' : 0,
    '성석동' : 0,
    '식사동' : 0,
    '신원동' : 0,
    '원흥동' : 0,
    '일산동' : 0,
    '장항동' : 0,
    '주교동' : 0,
    '주엽동' : 0,
    '중산동' : 0,
    '지축동' : 0,
    '탄현동' : 0,
    '토당동' : 0,
    '풍동' : 0,
    '행신동' : 0,
    '향동동' : 0,
    '화정동' : 0
}

# 해당 동은 1로 바꿔주기
temp[data_dong] = 1

# dataframe(series) 형태로 변환
data_f = pd.DataFrame([temp])

In [4]:
data_f

,year,전용면적,버스노선수,가좌동,고양동,관산동,대화동,덕은동,덕이동,도내동,...,주교동,주엽동,중산동,지축동,탄현동,토당동,풍동,행신동,향동동,화정동
0,2023,85,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# model에 넣어서 예측값 구하기
modelReload.predict(data_f)